# Generated by Django 5.2.3 on 2025-06-24 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_car_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
