# Generated by Django 5.2.3 on 2025-06-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recepie',
            old_name='recepie_description',
            new_name='receipe_description',
        ),
        migrations.RenameField(
            model_name='recepie',
            old_name='recepie_name',
            new_name='receipe_name',
        ),
        migrations.RemoveField(
            model_name='recepie',
            name='recepie_image',
        ),
        migrations.AddField(
            model_name='recepie',
            name='receipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipes/'),
        ),
    ]
