# Generated by Django 5.2.3 on 2025-06-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_recepie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepie',
            name='receipe_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
